name: 'Minikube setup with registry'
author: Enmasse Project
description: 'Installs minikube in Github Actions with custom registry.'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  minikube-version:
    description: 'Minikube version to install'
    required: false
    default: '1.9.2-0'
  k8s-version:
    description: 'Kubernetes version to install'
    required: false
    default: '1.18.0'
outputs:
  launcher:
    description: 'Command to execute to launch minikube'
runs:
  using: 'node12'
  main: 'src/index.js'
